Valentin-Gurduza/BeekeepingStore

eUseControl.BeekeepingStore/App_Start/RouteConfig.cs, eUseControl.BeekeepingStore/Views/Home/About.cshtml, eUseControl.BeekeepingStore/Views/Home/Blog.cshtml, eUseControl.BeekeepingStore/Views/Home/BlogDetails.cshtml, eUseControl.BeekeepingStore/Views/Home/Contact.cshtml, eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
Am adaugat contact,about,blog,blogdetails, si erau niste probleme unde unele randuri aratau eroare de context inexistent, acum ar trebui totul sa fie in regula
=> Fix si adaugare contact,about,blog

eUseControl.BeekeepingStore/Views/Home/About.cshtml
=> About change path

eUseControl.BeekeepingStore/Views/Home/Blog.cshtml, eUseControl.BeekeepingStore/Views/Home/BlogDetails.cshtml, eUseControl.BeekeepingStore/Views/Home/Contact.cshtml, eUseControl.BeekeepingStore/Views/Home/Index.cshtml
Change cshtml files path for landing scripts
=> Change cshtml files path for landing scripts

eUseControl.BeekeepingStore/Models/Product.cs, eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml, eUseControl.BeekeepingStore/Web.config
Adaugat noi lucruri la pagina principala
=> Adaugat noi lucruri la pagina principala

eUseControl.BeekeepingStore/Views/Home/About.cshtml
=> Adaugat informatii About us

eUseControl.BeekeepingStore/App_Start/RouteConfig.cs, eUseControl.BeekeepingStore/Controllers/AccountController.cs, eUseControl.BeekeepingStore/Controllers/HomeController.cs, eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/Views/Home/Login.cshtml, eUseControl.BeekeepingStore/Views/Home/Register.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj.user
=> login si register

eUseControl.BeekeepingStore/App_Start/BundleConfig.cs, eUseControl.BeekeepingStore/Global.asax.cs, eUseControl.BeekeepingStore/README.txt, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj, eUseControl.BeekeepingStore/packages.config
=> adaugare-bundle

eUseControl.BeekeepingStore/App_Start/BundleConfig.cs, eUseControl.BeekeepingStore/Content/style.css, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml
adaugat in BundleConfig fisierele css si am schimbat culoara barei de navigare la culoare alba deoarece a fost schimbata in gray
=> adaugare css content in BundleConfig

eUseControl.BeekeepingStore/Controllers/HomeController.cs, eUseControl.BeekeepingStore/Views/Home/Products.cshtml
=> afisare imagini

BeekeepingStore.sln, eUseControl.BeekeepingStore.BusinessLogic/BusinessLogic.cs, eUseControl.BeekeepingStore.BusinessLogic/Core/AdminApi.cs, eUseControl.BeekeepingStore.BusinessLogic/Core/UserApi.cs, eUseControl.BeekeepingStore.BusinessLogic/Interfaces/ISession.cs, eUseControl.BeekeepingStore.BusinessLogic/Properties/AssemblyInfo.cs, eUseControl.BeekeepingStore.BusinessLogic/SessionBL.cs, eUseControl.BeekeepingStore.BusinessLogic/eUseControl.BeekeepingStore.BusinessLogic.csproj, eUseControl.BeekeepingStore.Domain/Class1.cs, eUseControl.BeekeepingStore.Domain/Properties/AssemblyInfo.cs, eUseControl.BeekeepingStore.Domain/eUseControl.BeekeepingStore.Domain.csproj, eUseControl.BeekeepingStore.Helpers/Class1.cs, eUseControl.BeekeepingStore.Helpers/Properties/AssemblyInfo.cs, eUseControl.BeekeepingStore.Helpers/eUseControl.BeekeepingStore.Helpers.csproj, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
=> BusinessLogic

eUseControl.BeekeepingStore.BusinessLogic/Core/AdminApi.cs, eUseControl.BeekeepingStore.BusinessLogic/Core/UserApi.cs, eUseControl.BeekeepingStore.BusinessLogic/SessionBL.cs
=> Error fixes

eUseControl.BeekeepingStore.Domain/Entities/User/UserLogin.cs
=> public class

eUseControl.BeekeepingStore.BusinessLogic/BusinessLogic.cs, eUseControl.BeekeepingStore.BusinessLogic/DataContext.cs, eUseControl.BeekeepingStore.BusinessLogic/ErrorLog.cs, eUseControl.BeekeepingStore.BusinessLogic/Interfaces/ISession.cs, eUseControl.BeekeepingStore.BusinessLogic/Session.cs, eUseControl.BeekeepingStore.BusinessLogic/SessionBL.cs, eUseControl.BeekeepingStore.BusinessLogic/User.cs, eUseControl.BeekeepingStore.BusinessLogic/UserActivity.cs, eUseControl.BeekeepingStore.BusinessLogic/eUseControl.BeekeepingStore.BusinessLogic.csproj, eUseControl.BeekeepingStore.Domain/Entities/User/ULoginData.cs, eUseControl.BeekeepingStore.Domain/Entities/User/UProfileData.cs, eUseControl.BeekeepingStore.Domain/Entities/User/UUserData.cs, eUseControl.BeekeepingStore/Controllers/LoginController.cs
=> BusinessLogic implementare

eUseControl.BeekeepingStore/Controllers/HomeController.cs, eUseControl.BeekeepingStore/Views/Home/Cart.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Header.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
=> ShoppingCart

eUseControl.BeekeepingStore.BusinessLogic/BusinessLogic.cs, eUseControl.BeekeepingStore.BusinessLogic/Core/UserApi.cs
Business Logic UserAPI/BusinessLogic
=> Business Logic UserAPI/BusinessLogic

eUseControl.BeekeepingStore.BusinessLogic/User.cs, eUseControl.BeekeepingStore.BusinessLogic/UserActivity.cs, eUseControl.BeekeepingStore.Domain/Entities/User/UProfileData.cs, eUseControl.BeekeepingStore.Domain/Entities/User/UserLogin.cs, eUseControl.BeekeepingStore/Controllers/LoginController.cs, eUseControl.BeekeepingStore/Views/web.config
=> Error fix BL

eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Header.cshtml
Sters butonul search din home page deoarece nu sta pozitionat bine
=> Sters butonul search din home page deoarece nu sta pozitionat bine

eUseControl.BeekeepingStore.BusinessLogic/App.config, eUseControl.BeekeepingStore.BusinessLogic/DBModel/DbContext.cs, eUseControl.BeekeepingStore.BusinessLogic/DBModel/UserContext.cs, eUseControl.BeekeepingStore.BusinessLogic/eUseControl.BeekeepingStore.BusinessLogic.csproj, eUseControl.BeekeepingStore.BusinessLogic/packages.config, eUseControl.BeekeepingStore.Domain/App.config, eUseControl.BeekeepingStore.Domain/Entities/User/UDBTable.cs, eUseControl.BeekeepingStore.Domain/Enums/URole.cs, eUseControl.BeekeepingStore.Domain/eUseControl.BeekeepingStore.Domain.csproj, eUseControl.BeekeepingStore.Domain/packages.config, eUseControl.BeekeepingStore/Web.config, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj, eUseControl.BeekeepingStore/packages.config
EntityFramework nuget packages, DB
=> EntityFramework nuget packages, DB

eUseControl.BeekeepingStore.BusinessLogic/DBModel/DbContext.cs, eUseControl.BeekeepingStore.BusinessLogic/DBModel/UserContext.cs, eUseControl.BeekeepingStore/Web.config
=> Connect DB SQL

eUseControl.BeekeepingStore.BusinessLogic/Core/UserApi.cs, eUseControl.BeekeepingStore/Views/Account/Register.cshtml
baza de date, sa stocheze info despre inregistrare
=> baza de date, sa stocheze info despre inregistrare

eUseControl.BeekeepingStore/App_Start/RouteConfig.cs, eUseControl.BeekeepingStore/Content/modern-site.css, eUseControl.BeekeepingStore/Content/style.css, eUseControl.BeekeepingStore/Scripts/site.js, eUseControl.BeekeepingStore/Views/Home/Cart.cshtml, eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Footer.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Header.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
=> Am modernizat frontul

eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
=> Fix register

eUseControl.BeekeepingStore/Views/Home/Register.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
=> pagina register fix

eUseControl.BeekeepingStore.BusinessLogic/DataContext.cs, eUseControl.BeekeepingStore.BusinessLogic/Interfaces/IProduct.cs, eUseControl.BeekeepingStore.BusinessLogic/ProductBL.cs, eUseControl.BeekeepingStore.BusinessLogic/eUseControl.BeekeepingStore.BusinessLogic.csproj, eUseControl.BeekeepingStore.Domain/Entities/Product/Product.cs, eUseControl.BeekeepingStore.Domain/eUseControl.BeekeepingStore.Domain.csproj, eUseControl.BeekeepingStore/App_Start/BundleConfig.cs, eUseControl.BeekeepingStore/Controllers/ProductController.cs, eUseControl.BeekeepingStore/Controllers/ProductTestController.cs, eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/Views/Product/Create.cshtml, eUseControl.BeekeepingStore/Views/Product/Delete.cshtml, eUseControl.BeekeepingStore/Views/Product/Details.cshtml, eUseControl.BeekeepingStore/Views/Product/Edit.cshtml, eUseControl.BeekeepingStore/Views/Product/Index.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Header.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
Se pot adauga produse in baza de date, edita si sterge. La moment produsele se adauga insa nu apar pe pagina de producte pe care utilizatorul o poate vedea
=> Implementare produse in baza de date

eUseControl.BeekeepingStore/Views/Product/Details.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj.user
Am modificat astfel incat imaginea URL sa nu extinda containerul cu detalii despre produs
=> Am modificat astfel incat imaginea URL sa extinda containerul cu detalii despre produs

eUseControl.BeekeepingStore/Controllers/AccountController.cs, eUseControl.BeekeepingStore/Controllers/AdminController.cs, eUseControl.BeekeepingStore/Filters/AdminModAttribute.cs, eUseControl.BeekeepingStore/Filters/UserModAttribute.cs, eUseControl.BeekeepingStore/Filters/VisitorModAttribute.cs, eUseControl.BeekeepingStore/Scripts/site.js, eUseControl.BeekeepingStore/Views/Home/Index.cshtml, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj.user
Creat controllere admin si filtrele pentru Utilizator, Admin, si guest
=> Creat controllere admin si filtrele pentru Utilizator, Admin, si guest

eUseControl.BeekeepingStore.BusinessLogic/BusinessLogic.cs, eUseControl.BeekeepingStore.BusinessLogic/DataContext.cs, eUseControl.BeekeepingStore.BusinessLogic/ErrorLog.cs, eUseControl.BeekeepingStore.BusinessLogic/Interfaces/IWishlist.cs, eUseControl.BeekeepingStore.BusinessLogic/WishlistBL.cs, eUseControl.BeekeepingStore.BusinessLogic/eUseControl.BeekeepingStore.BusinessLogic.csproj, eUseControl.BeekeepingStore.Domain/Entities/User/Wishlist.cs, eUseControl.BeekeepingStore.Domain/eUseControl.BeekeepingStore.Domain.csproj, eUseControl.BeekeepingStore/Controllers/WishlistController.cs, eUseControl.BeekeepingStore/Views/Wishlist/Index.cshtml, eUseControl.BeekeepingStore/Web.config, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj
Implementare pagina wishlist (pagina de favorite), utilizatorul poate marca care produse sunt pe plac si se salveaza la favorite
=> Implementare pagina wishlist (pagina de favorite), utilizatorul poate marca care produse sunt pe plac si se salveaza la favorite

eUseControl.BeekeepingStore/Scripts/site.js, eUseControl.BeekeepingStore/Views/Wishlist/Index.cshtml
Am corectat site.js am incurcat niste cod de acolo cu alt fisier
=> Am corectat site.js am incurcat niste cod de acolo cu alt fisier

eUseControl.BeekeepingStore.BusinessLogic/App.config, eUseControl.BeekeepingStore.BusinessLogic/BlogBL.cs, eUseControl.BeekeepingStore.BusinessLogic/DataContext.cs, eUseControl.BeekeepingStore.BusinessLogic/Interfaces/IBlog.cs, eUseControl.BeekeepingStore.BusinessLogic/ProductBL.cs, eUseControl.BeekeepingStore.BusinessLogic/eUseControl.BeekeepingStore.BusinessLogic.csproj, eUseControl.BeekeepingStore.Domain/App.config, eUseControl.BeekeepingStore.Domain/Entities/Blog/BlogComment.cs, eUseControl.BeekeepingStore.Domain/Entities/Blog/BlogPost.cs, eUseControl.BeekeepingStore.Domain/eUseControl.BeekeepingStore.Domain.csproj, eUseControl.BeekeepingStore.Domain/packages.config, eUseControl.BeekeepingStore.Helpers/eUseControl.BeekeepingStore.Helpers.csproj, eUseControl.BeekeepingStore.Helpers/packages.config, eUseControl.BeekeepingStore/Controllers/BlogController.cs, eUseControl.BeekeepingStore/Controllers/HomeController.cs, eUseControl.BeekeepingStore/Filters/AdminModAttribute.cs, eUseControl.BeekeepingStore/Filters/UserModAttribute.cs, eUseControl.BeekeepingStore/Models/BlogCommentModel.cs, eUseControl.BeekeepingStore/Views/Blog/Index.cshtml, eUseControl.BeekeepingStore/Views/Blog/Post.cshtml, eUseControl.BeekeepingStore/Views/Home/Blog.cshtml, eUseControl.BeekeepingStore/Views/Shared/_Layout.cshtml, eUseControl.BeekeepingStore/Web.config, eUseControl.BeekeepingStore/eUseControl.BeekeepingStore.csproj, eUseControl.BeekeepingStore/packages.config
=> Implementarea inceput Blog.
